### ISSUE TITLE
[Question] Mushroom swamp generation

### ISSUE THREAD

**Issue by Nekkok** [CraftyG/vanilla_parity#21]
Is there anyway to disable them on the biome swamp? It's just a matter of prefference, I love this datapack :D

**Comment by CraftyG** [comment]
In the `features` array within the `swamp.json` file, there is a placed feature called `vnla_prt:swamp_huge_mushrooms`; removing that will disable the mushrooms generating inside the swamp. And since that's the only thing that's changed in the swamps, you can just simply delete the biome file from the data pack.

**Comment by Nekkok** [comment]
thank you!
